 


set termout on
set echo on
set verify off
set heading off


GRANT CREATE SESSION, CREATE TABLE TO PS IDENTIFIED BY PS;
CONNECT PS/PS@&1;
CREATE TABLE PSDBOWNER (DBNAME VARCHAR2(8) NOT NULL, OWNERID VARCHAR2(8) NOT NULL ) TABLESPACE PSDEFAULT;
CREATE UNIQUE INDEX PS_PSDBOWNER ON PSDBOWNER (DBNAME) TABLESPACE PSDEFAULT;

CONNECT system/&2@&1;
REVOKE CREATE SESSION, CREATE TABLE FROM PS;

ALTER USER PS QUOTA UNLIMITED ON PSDEFAULT;

exit
exit
exit