Remark * Script: epddl.sql  Oracle on NT
Remark * Date last modified: 01/02/2014

Remark * This script is used to create tablespaces for the PeopleSoft 9.2
Remark * Financials and Supply Chain Management Products.

Remark * NOTE: The sizing of the tablespaces here are only sample sizes that will
Remark *       hold the demo database tables.  This is not sized correctly for a
Remark *       production database.
 
Remark * Users can choose to use the autoextending tablespace feature.
Remark * The syntax is at the end of this script.

Remark * Change the datafile name as appropriate for your site.

set termout on
set echo off
set verify off
set heading off


CREATE TABLESPACE AMAPP DATAFILE '&3\&1\&2\amapp.dbf' SIZE 108M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE AMARCH DATAFILE '&3\&1\&2\amarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE AMLARGE DATAFILE '&3\&1\&2\amlarge.dbf' SIZE 46M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE AMWORK DATAFILE '&3\&1\&2\amwork.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE APAPP DATAFILE '&3\&1\&2\apapp.dbf' SIZE 27M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE APARCH DATAFILE '&3\&1\&2\aparch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE APLARGE DATAFILE '&3\&1\&2\aplarge.dbf' SIZE 25M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE APWORK DATAFILE '&3\&1\&2\apwork.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ARAPP DATAFILE '&3\&1\&2\arapp.dbf' SIZE 21M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ARARCH DATAFILE '&3\&1\&2\ararch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ARLARGE DATAFILE '&3\&1\&2\arlarge.dbf' SIZE 32M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ARWORK DATAFILE '&3\&1\&2\arwork.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE AUCAPP DATAFILE '&3\&1\&2\aucapp.dbf' SIZE 23M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE AUCLRGE DATAFILE '&3\&1\&2\auclrge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE BCAPP DATAFILE '&3\&1\&2\bcapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE BDAPP DATAFILE '&3\&1\&2\bdapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE BDLARGE DATAFILE '&3\&1\&2\bdlarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE BIAPP DATAFILE '&3\&1\&2\biapp.dbf' SIZE 15M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE BILARGE DATAFILE '&3\&1\&2\bilarge.dbf' SIZE 19M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE BIWORK DATAFILE '&3\&1\&2\biwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CAAPP DATAFILE '&3\&1\&2\caapp.dbf' SIZE 12M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CAWORK DATAFILE '&3\&1\&2\cawork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CFGAPP DATAFILE '&3\&1\&2\cfgapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CPAPP DATAFILE '&3\&1\&2\cpapp.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CPLARGE DATAFILE '&3\&1\&2\cplarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CSAPP DATAFILE '&3\&1\&2\csapp.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CSLARGE DATAFILE '&3\&1\&2\cslarge.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CSWORK DATAFILE '&3\&1\&2\cswork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CUAUDIT DATAFILE '&3\&1\&2\cuaudit.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CULARG1 DATAFILE '&3\&1\&2\cularg1.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CULARG2 DATAFILE '&3\&1\&2\cularg2.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CULARG3 DATAFILE '&3\&1\&2\cularg3.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE CULARGE DATAFILE '&3\&1\&2\cularge.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE DIAPP DATAFILE '&3\&1\&2\diapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE DPAPP DATAFILE '&3\&1\&2\dpapp.dbf' SIZE 19M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE DPLARGE DATAFILE '&3\&1\&2\dplarge.dbf' SIZE 12M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE DPWORK DATAFILE '&3\&1\&2\dpwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOAPP DATAFILE '&3\&1\&2\eoapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOBFAPP DATAFILE '&3\&1\&2\eobfapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOCFAPP DATAFILE '&3\&1\&2\eocfapp.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOCMAPP DATAFILE '&3\&1\&2\eocmapp.dbf' SIZE 11M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOCMLRG DATAFILE '&3\&1\&2\eocmlrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOCMWRK DATAFILE '&3\&1\&2\eocmwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOCUAPP DATAFILE '&3\&1\&2\eocuapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOCULRG DATAFILE '&3\&1\&2\eoculrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EODSAPP DATAFILE '&3\&1\&2\eodsapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EODSLRG DATAFILE '&3\&1\&2\eodslrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOECAPP DATAFILE '&3\&1\&2\eoecapp.dbf' SIZE 38M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOECLRG DATAFILE '&3\&1\&2\eoeclrg.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOECWRK DATAFILE '&3\&1\&2\eoecwrk.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOEIAPP DATAFILE '&3\&1\&2\eoeiapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOEILRG DATAFILE '&3\&1\&2\eoeilrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOEPAPP DATAFILE '&3\&1\&2\eoepapp.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOEPLRG DATAFILE '&3\&1\&2\eoeplrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOEPWRK DATAFILE '&3\&1\&2\eoepwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOEWAPP DATAFILE '&3\&1\&2\eoewapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOEWLRG DATAFILE '&3\&1\&2\eoewlrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOEWWRK DATAFILE '&3\&1\&2\eoewwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOIUAPP DATAFILE '&3\&1\&2\eoiuapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOIULRG DATAFILE '&3\&1\&2\eoiulrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOIUWRK DATAFILE '&3\&1\&2\eoiuwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOLARGE DATAFILE '&3\&1\&2\eolarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

REM Old carried forward
CREATE TABLESPACE EOLTAPP DATAFILE '&3\&1\&2\eoltapp.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOPPAPP DATAFILE '&3\&1\&2\eoppapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
REM Old carried forward
CREATE TABLESPACE EOPPLRG DATAFILE '&3\&1\&2\eopplrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOTPAPP DATAFILE '&3\&1\&2\eotpapp.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EOTPLRG DATAFILE '&3\&1\&2\eotplrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EXAPP DATAFILE '&3\&1\&2\exapp.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EXARCH DATAFILE '&3\&1\&2\exarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EXLARGE DATAFILE '&3\&1\&2\exlarge.dbf' SIZE 9M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE EXWORK DATAFILE '&3\&1\&2\exwork.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FAAPP DATAFILE '&3\&1\&2\faapp.dbf' SIZE 28M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FALARGE DATAFILE '&3\&1\&2\falarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FAWORK DATAFILE '&3\&1\&2\fawork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FGAPP DATAFILE '&3\&1\&2\fgapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FGARCH DATAFILE '&3\&1\&2\fgarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FGIMAGE DATAFILE '&3\&1\&2\fgimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FGLARGE DATAFILE '&3\&1\&2\fglarge.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FGTEMP DATAFILE '&3\&1\&2\fgtemp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FGWORK DATAFILE '&3\&1\&2\fgwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FIAPP DATAFILE '&3\&1\&2\fiapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FILARGE DATAFILE '&3\&1\&2\filarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FOAPP DATAFILE '&3\&1\&2\foapp.dbf' SIZE 14M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FOIMAGE DATAFILE '&3\&1\&2\foimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FOLARGE DATAFILE '&3\&1\&2\folarge.dbf' SIZE 22M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FOWORK DATAFILE '&3\&1\&2\fowork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FSAPP DATAFILE '&3\&1\&2\fsapp.dbf' SIZE 139M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FSAPP1 DATAFILE '&3\&1\&2\fsapp1.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FSLARGE DATAFILE '&3\&1\&2\fslarge.dbf' SIZE 41M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE FSWORK DATAFILE '&3\&1\&2\fswork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

REm Old Carried forward
CREATE TABLESPACE GIAPP DATAFILE '&3\&1\&2\giapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE GLAPP DATAFILE '&3\&1\&2\glapp.dbf' SIZE 74M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE GLARCH DATAFILE '&3\&1\&2\glarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE GLLARGE DATAFILE '&3\&1\&2\gllarge.dbf' SIZE 75M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE GLWORK DATAFILE '&3\&1\&2\glwork.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE GMAPP DATAFILE '&3\&1\&2\gmapp.dbf' SIZE 31M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE HRAPP DATAFILE '&3\&1\&2\hrapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE HRLARGE DATAFILE '&3\&1\&2\hrlarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE HTAPP DATAFILE '&3\&1\&2\htapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE INAPP DATAFILE '&3\&1\&2\inapp.dbf' SIZE 40M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE INARCH DATAFILE '&3\&1\&2\inarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE INLARGE DATAFILE '&3\&1\&2\inlarge.dbf' SIZE 37M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE INWORK DATAFILE '&3\&1\&2\inwork.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE LCAPP DATAFILE '&3\&1\&2\lcapp.dbf' SIZE 135M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE LCLARGE DATAFILE '&3\&1\&2\lclarge.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE MGAPP DATAFILE '&3\&1\&2\mgapp.dbf' SIZE 32M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE MGLARGE DATAFILE '&3\&1\&2\mglarge.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE MPAPP DATAFILE '&3\&1\&2\mpapp.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE MPLARGE DATAFILE '&3\&1\&2\mplarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE MPWORK DATAFILE '&3\&1\&2\mpwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE OEAPP DATAFILE '&3\&1\&2\oeapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE OMAPP DATAFILE '&3\&1\&2\omapp.dbf' SIZE 26M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE OMLARGE DATAFILE '&3\&1\&2\omlarge.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE OMWORK DATAFILE '&3\&1\&2\omwork.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PBAPP DATAFILE '&3\&1\&2\pbapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PBIMAGE DATAFILE '&3\&1\&2\pbimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PBLARGE DATAFILE '&3\&1\&2\pblarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PBWORK DATAFILE '&3\&1\&2\pbwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PCAPP DATAFILE '&3\&1\&2\pcapp.dbf' SIZE 39M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PCARCH DATAFILE '&3\&1\&2\pcarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PCLARGE DATAFILE '&3\&1\&2\pclarge.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PCWORK DATAFILE '&3\&1\&2\pcwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PGMAPP DATAFILE '&3\&1\&2\pgmapp.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PGMLARGE DATAFILE '&3\&1\&2\pgmlarge.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PGMWORK DATAFILE '&3\&1\&2\pgmwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PIPSAPP DATAFILE '&3\&1\&2\pipsapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PIPSLRG DATAFILE '&3\&1\&2\pipslrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PIPSWORK DATAFILE '&3\&1\&2\pipswork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PLAPP DATAFILE '&3\&1\&2\plapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PLLARGE DATAFILE '&3\&1\&2\pllarge.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PLWORK DATAFILE '&3\&1\&2\plwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE POAPP DATAFILE '&3\&1\&2\poapp.dbf' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE POLARGE DATAFILE '&3\&1\&2\polarge.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE POWORK DATAFILE '&3\&1\&2\powork.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PSIMAGE DATAFILE '&3\&1\&2\psimage.dbf' SIZE 2500M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PSIMAGE2 DATAFILE '&3\&1\&2\psimage2.dbf' SIZE 3100M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PSMATVW DATAFILE '&3\&1\&2\psmatvw.dbf' SIZE 250M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PSIMGR DATAFILE '&3\&1\&2\psimgr.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
 
CREATE TABLESPACE PSINDEX DATAFILE '&3\&1\&2\psindex.dbf' SIZE 5133M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PSWORK DATAFILE '&3\&1\&2\pswork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTAMSG DATAFILE '&3\&1\&2\ptamsg.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTAPP DATAFILE '&3\&1\&2\ptapp.dbf' SIZE 18M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTAPPE DATAFILE '&3\&1\&2\ptappe.dbf' SIZE 9M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTAUDIT DATAFILE '&3\&1\&2\ptaudit.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTCMSTAR DATAFILE '&3\&1\&2\ptcmstar.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTLOCK DATAFILE '&3\&1\&2\ptlock.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTPRC DATAFILE '&3\&1\&2\ptprc.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

REM Old Carried forward
CREATE TABLESPACE PTPRCS DATAFILE '&3\&1\&2\ptprcs.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTPRJWK DATAFILE '&3\&1\&2\ptprjwk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTRPTS DATAFILE '&3\&1\&2\ptrpts.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTTBL DATAFILE '&3\&1\&2\pttbl.dbf' SIZE 450M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTTLRG DATAFILE '&3\&1\&2\pttlrg.dbf' SIZE 2214M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTTREE DATAFILE '&3\&1\&2\pttree.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PTWORK DATAFILE '&3\&1\&2\ptwork.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PVAPP DATAFILE '&3\&1\&2\pvapp.dbf' SIZE 22M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PVLARGE DATAFILE '&3\&1\&2\pvlarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE PYAPP DATAFILE '&3\&1\&2\pyapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

REM old carried forward
CREATE TABLESPACE PY0LRG DATAFILE '&3\&1\&2\py0lrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE RBAPP DATAFILE '&3\&1\&2\rbapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE RBTEMP DATAFILE '&3\&1\&2\rbtemp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE REAPP DATAFILE '&3\&1\&2\reapp.dbf' SIZE 14M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE REIMAGE DATAFILE '&3\&1\&2\reimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE RELARGE DATAFILE '&3\&1\&2\relarge.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE REWORK DATAFILE '&3\&1\&2\rework.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE ROAPP DATAFILE '&3\&1\&2\roapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE RSAPP DATAFILE '&3\&1\&2\rsapp.dbf' SIZE 19M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE RSFAPP DATAFILE '&3\&1\&2\rsfapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE RSLARGE DATAFILE '&3\&1\&2\rslarge.dbf' SIZE 13M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE RSWORK DATAFILE '&3\&1\&2\rswork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE SACAPP DATAFILE '&3\&1\&2\sacapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE SACLRGE DATAFILE '&3\&1\&2\saclrge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE SPAPP DATAFILE '&3\&1\&2\spapp.dbf' SIZE 27M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE SPLARGE DATAFILE '&3\&1\&2\splarge.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TDAPP DATAFILE '&3\&1\&2\tdapp.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TDLARGE DATAFILE '&3\&1\&2\tdlarge.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TDWORK DATAFILE '&3\&1\&2\tdwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TLAPP DATAFILE '&3\&1\&2\tlapp.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TLWORK DATAFILE '&3\&1\&2\tlwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TPMAPP DATAFILE '&3\&1\&2\tpmapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TRAPP DATAFILE '&3\&1\&2\trapp.dbf' SIZE 120M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TRARCH DATAFILE '&3\&1\&2\trarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TRIMAGE DATAFILE '&3\&1\&2\trimage.dbf' SIZE 15M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
 
CREATE TABLESPACE TRLARGE DATAFILE '&3\&1\&2\trlarge.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE TRWORK DATAFILE '&3\&1\&2\trwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE WMAPP DATAFILE '&3\&1\&2\wmapp.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE WMIMAGE DATAFILE '&3\&1\&2\wmimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE WMLARGE DATAFILE '&3\&1\&2\wmlarge.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE WMWORK DATAFILE '&3\&1\&2\wmwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE WSAPP DATAFILE '&3\&1\&2\wsapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE WSLARGE DATAFILE '&3\&1\&2\wslarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TEMPORARY TABLESPACE PSGTT01 TEMPFILE '&3\&1\&2\psgtt01.dbf' SIZE 500M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
/

Rem * Users can choose to use the autoextending tablespace feature
Rem * by uncommenting the following lines.

ALTER DATABASE DATAFILE '&3\&1\&2\amapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\amarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\amlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\amwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\apapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\aparch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\aplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\apwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\arapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ararch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\arlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\arwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\aucapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\auclrge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\bcapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\bdapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\bdlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\biapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\bilarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\biwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\caapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cawork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cfgapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\csapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cuaudit.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cularg1.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cularg2.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cularg3.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\cularge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\diapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\dpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\dplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\dpwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\eoapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eobfapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocfapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocmlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocmwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocuapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoculrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eodsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eodslrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoecapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoeclrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoecwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoeiapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoeilrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoepapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoeplrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoepwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoewapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoewlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoewwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoiuapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoiulrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoiuwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eolarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REM Old carried forward
ALTER DATABASE DATAFILE '&3\&1\&2\eoltapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoppapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REM Old carried forward
ALTER DATABASE DATAFILE '&3\&1\&2\eopplrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eotpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eotplrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\exapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\exarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\exlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\exwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\faapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\falarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fawork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fgapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fgarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fgimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fglarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fgtemp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fgwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fiapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\filarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\foapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\foimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\folarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fowork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\fsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\fsapp1.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\fslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\fswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REm Old Carried forward
ALTER DATABASE DATAFILE '&3\&1\&2\giapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\glapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\glarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\gllarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\glwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\gmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\hrlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\htapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\inapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\inarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\inlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\inwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\lcapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\lclarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\mgapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\mglarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\mpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\mplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\mpwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\oeapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\omapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\omlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\omwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pbapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pbimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pblarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pbwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pcapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pcarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pclarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pcwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pgmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\pgmlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\pgmwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pipsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\pipslrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\pipswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\plapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\pllarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\plwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\poapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\polarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\powork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\psimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\psimage2.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\psmatvw.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\psimgr.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\psindex.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptamsg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptappe.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptaudit.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptcmstar.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptlock.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptprc.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REM Old Carried forward
ALTER DATABASE DATAFILE '&3\&1\&2\ptprcs.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
ALTER DATABASE DATAFILE '&3\&1\&2\ptprjwk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptrpts.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pttbl.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pttlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pttree.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\ptwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pvapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pvlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\pyapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REM old carried forward
ALTER DATABASE DATAFILE '&3\&1\&2\py0lrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\rbapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\rbtemp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\reapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\reimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\relarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\rework.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\roapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\rsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\rsfapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\rslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\rswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\sacapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\saclrge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\spapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\splarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\tdapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\tdlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\tdwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\tlapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\tlwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\tpmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\trapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\trarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\trimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\trlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\trwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\wmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\wmimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\wmlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\wmwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\wsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

ALTER DATABASE DATAFILE '&3\&1\&2\wslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REM If this tempfile needs to be altered it can only be done with an Oracle User that has SYSDBA privileges.
ALTER DATABASE TEMPFILE '&3\&1\&2\psgtt01.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

exit