
       


set termout on
set echo off
set verify off
set heading off

CREATE TABLESPACE AAAPP DATAFILE '&3\&1\&2\aaapp.dbf' SIZE 22M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE AALARGE DATAFILE '&3\&1\&2\aalarge.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ADAPP DATAFILE '&3\&1\&2\adapp.dbf' SIZE 60M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE AMAPP DATAFILE '&3\&1\&2\amapp.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE AVAPP DATAFILE '&3\&1\&2\avapp.dbf' SIZE 19M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE BDAPP DATAFILE '&3\&1\&2\bdapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE BNAPP DATAFILE '&3\&1\&2\bnapp.dbf' SIZE 52M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE BNLARGE DATAFILE '&3\&1\&2\bnlarge.dbf' SIZE 32M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
REM OLD carried forward 
CREATE TABLESPACE BPAPP1 DATAFILE '&3\&1\&2\bpapp1.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CCAPP DATAFILE '&3\&1\&2\ccapp.dbf' SIZE 100M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE COAPP DATAFILE '&3\&1\&2\coapp.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CUAUDIT DATAFILE '&3\&1\&2\cuaudit.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CULARG1 DATAFILE '&3\&1\&2\cularg1.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CULARG2 DATAFILE '&3\&1\&2\cularg2.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CULARG3 DATAFILE '&3\&1\&2\cularg3.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CULARGE DATAFILE '&3\&1\&2\cularge.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE DIAPP DATAFILE '&3\&1\&2\diapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE DTAPP DATAFILE '&3\&1\&2\dtapp.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOAPP DATAFILE '&3\&1\&2\eoapp.dbf' SIZE 25M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOBFAPP DATAFILE '&3\&1\&2\eobfapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCFAPP DATAFILE '&3\&1\&2\eocfapp.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCMAPP DATAFILE '&3\&1\&2\eocmapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCMLRG DATAFILE '&3\&1\&2\eocmlrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCMWRK DATAFILE '&3\&1\&2\eocmwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCUAPP DATAFILE '&3\&1\&2\eocuapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCULRG DATAFILE '&3\&1\&2\eoculrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
REM OLD carried forward 
CREATE TABLESPACE EODITBL DATAFILE '&3\&1\&2\eoditbl.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EODSAPP DATAFILE '&3\&1\&2\eodsapp.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EODSLRG DATAFILE '&3\&1\&2\eodslrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOECAPP DATAFILE '&3\&1\&2\eoecapp.dbf' SIZE 25M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOECLRG DATAFILE '&3\&1\&2\eoeclrg.dbf' SIZE 100M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOECWRK DATAFILE '&3\&1\&2\eoecwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEIAPP DATAFILE '&3\&1\&2\eoeiapp.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEILRG DATAFILE '&3\&1\&2\eoeilrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEWAPP DATAFILE '&3\&1\&2\eoewapp.dbf' SIZE 9M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEWLRG DATAFILE '&3\&1\&2\eoewlrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEWWRK DATAFILE '&3\&1\&2\eoewwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOIUAPP DATAFILE '&3\&1\&2\eoiuapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOIULRG DATAFILE '&3\&1\&2\eoiulrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOIUWRK DATAFILE '&3\&1\&2\eoiuwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOLARGE DATAFILE '&3\&1\&2\eolarge.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOLTAPP DATAFILE '&3\&1\&2\eoltapp.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOPPAPP DATAFILE '&3\&1\&2\eoppapp.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOPPLRG DATAFILE '&3\&1\&2\eopplrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOTPAPP DATAFILE '&3\&1\&2\eotpapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOTPLRG DATAFILE '&3\&1\&2\eotplrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EPAPP DATAFILE '&3\&1\&2\epapp.dbf' SIZE 15M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EPLARGE DATAFILE '&3\&1\&2\eplarge.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ERAPP DATAFILE '&3\&1\&2\erapp.dbf' SIZE 13M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ERLARGE DATAFILE '&3\&1\&2\erlarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ERWORK DATAFILE '&3\&1\&2\erwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FAAPP DATAFILE '&3\&1\&2\faapp.dbf' SIZE 100M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FALARGE DATAFILE '&3\&1\&2\falarge.dbf' SIZE 15M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FGAPP DATAFILE '&3\&1\&2\fgapp.dbf' SIZE 35M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FGLARGE DATAFILE '&3\&1\&2\fglarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FSAPP DATAFILE '&3\&1\&2\fsapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE GIAPP DATAFILE '&3\&1\&2\giapp.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE GPAPP DATAFILE '&3\&1\&2\gpapp.dbf' SIZE 600M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE GPDEAPP DATAFILE '&3\&1\&2\gpdeapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HPAPP DATAFILE '&3\&1\&2\hpapp.dbf' SIZE 75M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP DATAFILE '&3\&1\&2\hrapp.dbf' SIZE 350M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP1 DATAFILE '&3\&1\&2\hrapp1.dbf' SIZE 22M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP2 DATAFILE '&3\&1\&2\hrapp2.dbf' SIZE 18M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP3 DATAFILE '&3\&1\&2\hrapp3.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP4 DATAFILE '&3\&1\&2\hrapp4.dbf' SIZE 16M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP5 DATAFILE '&3\&1\&2\hrapp5.dbf' SIZE 13M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP6 DATAFILE '&3\&1\&2\hrapp6.dbf' SIZE 35M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP7 DATAFILE '&3\&1\&2\hrapp7.dbf' SIZE 100M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRIMAGE DATAFILE '&3\&1\&2\hrimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRLARG1 DATAFILE '&3\&1\&2\hrlarg1.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRLARGE DATAFILE '&3\&1\&2\hrlarge.dbf' SIZE 91M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRSAPP DATAFILE '&3\&1\&2\hrsapp.dbf' SIZE 64M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRSARCH DATAFILE '&3\&1\&2\hrsarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRSLARGE DATAFILE '&3\&1\&2\hrslarge.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRSWORK DATAFILE '&3\&1\&2\hrswork.dbf' SIZE 15M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRWORK DATAFILE '&3\&1\&2\hrwork.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HTAPP DATAFILE '&3\&1\&2\htapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE INAPP DATAFILE '&3\&1\&2\inapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PAAPP DATAFILE '&3\&1\&2\paapp.dbf' SIZE 59M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PALARGE DATAFILE '&3\&1\&2\palarge.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PCAPP DATAFILE '&3\&1\&2\pcapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PCLARGE DATAFILE '&3\&1\&2\pclarge.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PIAPP DATAFILE '&3\&1\&2\piapp.dbf' SIZE 9M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PILARGE DATAFILE '&3\&1\&2\pilarge.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PIWORK DATAFILE '&3\&1\&2\piwork.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE POAPP DATAFILE '&3\&1\&2\poapp.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMAGE DATAFILE '&3\&1\&2\psimage.dbf' SIZE 500M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMAGE2 DATAFILE '&3\&1\&2\psimage2.dbf' SIZE 1800M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSMATVW DATAFILE '&3\&1\&2\psmatvw.dbf' SIZE 250M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMGR DATAFILE '&3\&1\&2\psimgr.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSINDEX DATAFILE '&3\&1\&2\psindex.dbf' SIZE 3500M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAMSG DATAFILE '&3\&1\&2\ptamsg.dbf' SIZE 43M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAPP DATAFILE '&3\&1\&2\ptapp.dbf' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAPPE DATAFILE '&3\&1\&2\ptappe.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAUDIT DATAFILE '&3\&1\&2\ptaudit.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTCMSTAR DATAFILE '&3\&1\&2\ptcmstar.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTLOCK DATAFILE '&3\&1\&2\ptlock.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTPRC DATAFILE '&3\&1\&2\ptprc.dbf' SIZE 12M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTPRJWK DATAFILE '&3\&1\&2\ptprjwk.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTRPTS DATAFILE '&3\&1\&2\ptrpts.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTBL DATAFILE '&3\&1\&2\pttbl.dbf' SIZE 264M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTLRG DATAFILE '&3\&1\&2\pttlrg.dbf' SIZE 600M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTREE DATAFILE '&3\&1\&2\pttree.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTWORK DATAFILE '&3\&1\&2\ptwork.dbf' SIZE 12M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PVAPP DATAFILE '&3\&1\&2\pvapp.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PY0LRG DATAFILE '&3\&1\&2\py0lrg.dbf' SIZE 196M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PYAPP DATAFILE '&3\&1\&2\pyapp.dbf' SIZE 110M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PYLARGE DATAFILE '&3\&1\&2\pylarge.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PYWORK DATAFILE '&3\&1\&2\pywork.dbf' SIZE 30M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE SAAPP DATAFILE '&3\&1\&2\saapp.dbf' SIZE 100M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE SACAPP DATAFILE '&3\&1\&2\sacapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE SALARGE DATAFILE '&3\&1\&2\salarge.dbf' SIZE 9M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE SRAPP DATAFILE '&3\&1\&2\srapp.dbf' SIZE 151M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE STAPP DATAFILE '&3\&1\&2\stapp.dbf' SIZE 32M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE STLARGE DATAFILE '&3\&1\&2\stlarge.dbf' SIZE 13M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE STWORK DATAFILE '&3\&1\&2\stwork.dbf' SIZE 17M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE TLAPP DATAFILE '&3\&1\&2\tlapp.dbf' SIZE 230M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE TLLARGE DATAFILE '&3\&1\&2\tllarge.dbf' SIZE 40M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE TLWORK DATAFILE '&3\&1\&2\tlwork.dbf' SIZE 100M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE WAAPP DATAFILE '&3\&1\&2\waapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TEMPORARY TABLESPACE PSGTT01 TEMPFILE '&3\&1\&2\psgtt01.dbf' SIZE 500M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
/

REM Users can choose to use the autoextending tablespace feature.

ALTER DATABASE DATAFILE '&3\&1\&2\aaapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\aalarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\adapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\amapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\avapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\bdapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\bnapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\bnlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REM OLD carried forward
ALTER DATABASE DATAFILE '&3\&1\&2\bpapp1.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED; 

ALTER DATABASE DATAFILE '&3\&1\&2\ccapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\coapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\cuaudit.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\cularg1.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\cularg2.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\cularg3.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\cularge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\diapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\dtapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eobfapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocfapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocmlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocmwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eocuapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoculrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REM OLD carried forward 
ALTER DATABASE DATAFILE '&3\&1\&2\eoditbl.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eodsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eodslrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoecapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoeclrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoecwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoeiapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoeilrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoewapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoewlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoewwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoiuapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoiulrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoiuwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eolarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoltapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eoppapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eopplrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eotpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eotplrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\epapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\eplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\erapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\erlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\erwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\faapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\falarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\fgapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\fglarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\fsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\giapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\gpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\gpdeapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp1.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp2.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp3.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp4.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp5.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp6.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrapp7.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrlarg1.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrsarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\hrwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\htapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\inapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\paapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\palarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pcapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pclarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\piapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pilarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\piwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\poapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\psimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\psimage2.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\psmatvw.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\psimgr.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\psindex.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptamsg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptappe.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptaudit.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptcmstar.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptlock.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptprc.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptprjwk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptrpts.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pttbl.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pttlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pttree.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\ptwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pvapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\py0lrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pyapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pylarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\pywork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\saapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\sacapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\salarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\srapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\stapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\stlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\stwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\tlapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\tllarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\tlwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE '&3\&1\&2\waapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REM If this tempfile needs to be altered it can only be done with an Oracle User that has SYSDBA privileges.
ALTER DATABASE TEMPFILE '&3\&1\&2\psgtt01.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

exit