 
 


set termout on
set echo off
set verify off
set heading off

CREATE ROLE PSADMIN;
GRANT 
CREATE SESSION, 
CREATE  TABLE, 
CREATE  PROCEDURE, 
CREATE  SYNONYM,
CREATE  VIEW, 
CREATE  TRIGGER, 
CREATE DATABASE LINK,
CREATE MATERIALIZED VIEW 
TO PSADMIN ;

EXEC DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE -
    (GRANTEE_NAME => 'PSADMIN', PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER', -
     ADMIN_OPTION => TRUE);

Spool Off
exit