 
 


set termout on
set echo off
set verify off
set heading off


CREATE TABLESPACE PSIMAGE DATAFILE '&3\&1\&2\psimage.dbf' SIZE 250M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMAGE2 DATAFILE '&3\&1\&2\psimage2.dbf' SIZE 400M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSMATVW  DATAFILE '&3\&1\&2\psmatvw.dbf' SIZE 250M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSINDEX DATAFILE '&3\&1\&2\psindex.dbf' SIZE 2500M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAPP DATAFILE '&3\&1\&2\ptapp.dbf' SIZE 40M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTPRC DATAFILE '&3\&1\&2\ptprc.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTRPTS DATAFILE '&3\&1\&2\ptrpts.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTBL DATAFILE '&3\&1\&2\pttbl.dbf' SIZE 200M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSWORK DATAFILE '&3\&1\&2\pswork.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTLOCK DATAFILE '&3\&1\&2\ptlock.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAMSG DATAFILE '&3\&1\&2\ptamsg.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAPPE DATAFILE '&3\&1\&2\ptappe.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTLRG DATAFILE '&3\&1\&2\pttlrg.dbf' SIZE 80M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTREE DATAFILE '&3\&1\&2\pttree.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTWORK DATAFILE '&3\&1\&2\ptwork.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTCMSTAR DATAFILE '&3\&1\&2\ptcmstar.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTPRJWK DATAFILE '&3\&1\&2\ptprjwk.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAUDIT DATAFILE '&3\&1\&2\ptaudit.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMGR DATAFILE '&3\&1\&2\psimgr.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TEMPORARY TABLESPACE PSGTT01 TEMPFILE '&3\&1\&2\psgtt01.dbf' SIZE 500M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
/
ALTER DATABASE DATAFILE '&3\&1\&2\psimage.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\psimage2.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\psmatvw.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\psindex.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptapp.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptprc.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptrpts.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\pttbl.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\pswork.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptlock.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptamsg.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptappe.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\pttlrg.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\pttree.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptwork.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptcmstar.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptprjwk.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\ptaudit.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE DATAFILE '&3\&1\&2\psimgr.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/
ALTER DATABASE TEMPFILE '&3\&1\&2\psgtt01.dbf'
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
/

Spool Off
exit
