-- ***************************************************************
--  This software and related documentation are provided under a
--  license agreement containing restrictions on use and
--  disclosure and are protected by intellectual property
--  laws. Except as expressly permitted in your license agreement
--  or allowed by law, you may not use, copy, reproduce,
--  translate, broadcast, modify, license, transmit, distribute,
--  exhibit, perform, publish or display any part, in any form or
--  by any means. Reverse engineering, disassembly, or
--  decompilation of this software, unless required by law for
--  interoperability, is prohibited.
--  The information contained herein is subject to change without
--  notice and is not warranted to be error-free. If you find any
--  errors, please report them to us in writing.
--  
--  Copyright (C) 1988, 2017, Oracle and/or its affiliates.
--  All Rights Reserved.
-- ***************************************************************
 
 
--                                                                    
-- ******************************************************************
-- ******************************************************************
--
--                          
--
--                                                                  
--
-- ******************************************************************

REMARK -- Replace <PDB_SERVICE_NAME> with your Pluggable database name.
REMARK -- Replace <drive> with your Windows Drive.

REMARK * Use this script to create tablespaces for a PT8 PTDMO database
REMARK * Change <drive> and <SID> to the appropriate values for your system

set echo on
spool ptddl.log

REMARK * This section comprises the tablespaces that are specific to TOOLS

CREATE TABLESPACE PSIMAGE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psimage.dbf' SIZE 250M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMAGE2 DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psimage2.dbf' SIZE 400M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSMATVW  DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psmatvw.dbf' SIZE 250M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSINDEX DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psindex.dbf' SIZE 2500M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAPP DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptapp.dbf' SIZE 40M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTPRC DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptprc.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTRPTS DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptrpts.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTBL DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\pttbl.dbf' SIZE 200M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSWORK DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\pswork.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTLOCK DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptlock.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAMSG DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptamsg.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAPPE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptappe.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTLRG DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\pttlrg.dbf' SIZE 80M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTREE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\pttree.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTWORK DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptwork.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTCMSTAR DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptcmstar.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTPRJWK DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptprjwk.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAUDIT DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptaudit.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMGR DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psimgr.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TEMPORARY TABLESPACE PSGTT01 TEMPFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psgtt01.dbf' SIZE 500M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
/

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psimage.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psimage2.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psmatvw.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psindex.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptapp.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptprc.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptrpts.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\pttbl.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\pswork.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptlock.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptamsg.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptappe.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\pttlrg.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\pttree.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptwork.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptcmstar.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptprjwk.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\ptaudit.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psimgr.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /
REMARK If this tempfile needs to be altered it can only be done with an Oracle User that has SYSDBA privileges.
REMARK ALTER DATABASE TEMPFILE '<drive>:\oradata\<SID>\<PDB_SERVICE_NAME>\psgtt01.dbf'
REMARK AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
REMARK /

Spool Off
